# .gitlab-ci.yml

image: python:3.8

stages:
  - build
  - test

before_script:
  - python --version
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Build or setup steps go here"

pytest:
  stage: test
  script:
    - pytest
